# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lillymol_tests.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lillymol_tests.proto", :syntax => :proto3) do
    add_message "lillymol_tests.TestCase" do
      proto3_optional :name, :string, 1
      repeated :preamble, :string, 2
      repeated :args, :string, 3
      proto3_optional :difftool, :string, 4
      repeated :comment, :string, 5
      repeated :ignore_file, :string, 6
      proto3_optional :non_zero_rc_expected, :bool, 7
      proto3_optional :broken_do_not_evaluate, :bool, 8
      proto3_optional :executable, :string, 14
      repeated :default_command_components, :string, 15
    end
    add_message "lillymol_tests.TestCases" do
      proto3_optional :executable, :string, 1
      repeated :test, :message, 2, "lillymol_tests.TestCase"
      proto3_optional :difftool, :string, 3
      proto3_optional :difftool_options, :string, 6
      repeated :default_command_components, :string, 4
      proto3_optional :broken_do_not_evaluate, :bool, 5
      proto3_optional :only_inside_lilly, :bool, 7
    end
  end
end

module LillymolTests
  TestCase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lillymol_tests.TestCase").msgclass
  TestCases = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lillymol_tests.TestCases").msgclass
end
